name: Testomatio Tests
on:
  workflow_dispatch:
    inputs:
      grep:
        description: "Scenario tags to run (e.g. @smoke)"
        required: false
        default: ""
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
          libasound2t64 \
          libffi8 \
          libx264-dev \
          libnss3 \
          libatk-bridge2.0-0 \
          libgtk-3-0 \
          libx11-xcb1 \
          libxcb-dri3-0 \
          libdrm2 \
          libxcomposite1 \
          libxdamage1 \
          libxrandr2 \
          libgbm1 \
          libpango-1.0-0 \
          libcairo2
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            playwright-${{ runner.os }}-
      - name: Install Playwright Browsers
        run: npx playwright install
      - name: Run Cucumber tests
        run: npm run test
        env:
          TESTOMATIO: ${{ secrets.TESTOMATIO }}
          TESTOMATIO_RUN: ${{ github.event.inputs.run }}
          TESTOMATIO_URL: ${{ secrets.TESTOMATIO_URL }}
