name: Testomatio Tests
on:
  workflow_dispatch:
    inputs:
      grep:
        description: "Scenario tags to run (e.g. @smoke)"
        required: false
        default: ""
      run:
        required: false
      testomatio:
        required: false
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            playwright-${{ runner.os }}-
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Cucumber tests with Testomat reporter
        run: npx run test
        env:
          TESTOMATIO: ${{ secrets.TESTOMATIO }}
          TESTOMATIO_RUN: ${{ github.event.inputs.run }}
          TESTOMATIO_URL: ${{ secrets.TESTOMATIO_URL }}
